// DOM Selectors
const jobInput = document.getElementById('jobTitle');
const submitBtn = document.getElementById('submitBtn');
const btnText = document.getElementById('btnText');
const loader = document.getElementById('loader');
const resultContainer = document.getElementById('resultContainer');
const output = document.getElementById('output');
const errorDiv = document.getElementById('error');
const copyBtn = document.getElementById('copyBtn');

const BACKEND_URL = "https://interviewgen-backend.vercel.app/api/generate";

async function generateQuestions() {
    const title = jobInput.value.trim();
    if (!title) {
        showError("Please enter a job title.");
        return;
    }

    toggleLoading(true);
    errorDiv.classList.add('hidden');
    resultContainer.classList.add('hidden');

    try {
        // Send request to your secure backend instead of OpenRouter directly
        const response = await fetch(BACKEND_URL, {
            method: "POST",
            headers: {
                "Content-Type": "application/json"
            },
            body: JSON.stringify({ title: title })
        });

        if (!response.ok) throw new Error("Backend request failed");

        const data = await response.json();
        
        // Extract the content generated by the AI model
        const text = data.choices[0].message.content;

        if (text.includes("INVALID")) {
            showError("Please enter a valid job title (e.g. Product Manager, Software Engineer)");
        } else {
            output.textContent = text.trim();
            resultContainer.classList.remove('hidden');
        }
    } catch (err) {
        showError("Failed to generate questions. Please try again.");
        console.error(err);
    } finally {
        toggleLoading(false);
    }
}

function toggleLoading(isLoading) {
    submitBtn.disabled = isLoading;
    btnText.classList.toggle('hidden', isLoading);
    loader.classList.toggle('hidden', !isLoading);
}

function showError(message) {
    errorDiv.textContent = message;
    errorDiv.classList.remove('hidden');
}

function copyToClipboard() {
    const text = output.textContent;
    navigator.clipboard.writeText(text).then(() => {
        const original = copyBtn.innerHTML;
        copyBtn.innerHTML = '✅ Copied!';
        setTimeout(() => copyBtn.innerHTML = original, 2000);
    });
}

// Event Listeners
submitBtn.addEventListener('click', generateQuestions);

jobInput.addEventListener('keypress', (e) => {
    if (e.key === 'Enter') generateQuestions();
});

copyBtn.addEventListener('click', copyToClipboard);
